azure_subscription_id="${AZURE_SUBSCRIPTION_ID}"
azure_client_id="${AZURE_CLIENT_ID}"
azure_client_secret="${AZURE_CLIENT_SECRET}"
azure_tenant_id="${AZURE_TENANT_ID}"
resource_group_name="${resource_group_name}"
resource_group_location="${resource_group_location}"
vnet_name="${vnet_name}"
vnet_location="${vnet_location}"
